const DisputeStatus = {
    ASSIGNED: 'ASSIGNED',
    DISPUTE_RECEIVED_MERCHANT: 'DISPUTE_RECEIVED_MERCHANT',
    DISPUTE_RECEIVED_UNASSIGNED: 'DISPUTE_RECEIVED_UNASSIGNED',
    EVENT_CHANGED_ASSIGNED_STAFF:'EVENT_CHANGED_ASSIGNED_STAFF',
    STATUS_CHANGED: 'STATUS_CHANGED',
    EVENT_CHANGED: 'EVENT_CHANGED',
    DISPUTE_UPDATED: 'DISPUTE_UPDATED',
    ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
    DETAILS_EDITED: 'DETAILS_EDITED',
    ESCALATED: 'ESCALATED',
    RESOLVED: 'RESOLVED',
    REOPENED: 'REOPENED',
    COMMENTED: 'COMMENTED'
};

export default DisputeStatus;